listener 8883 0.0.0.0
cafile d:/IDP/IDP 2/backend/mosquitto/certs/ca.crt
certfile d:/IDP/IDP 2/backend/mosquitto/certs/server.crt
keyfile d:/IDP/IDP 2/backend/mosquitto/certs/server.key
tls_version tlsv1.2
require_certificate false

allow_anonymous false
password_file d:/IDP/IDP 2/backend/mosquitto/passwd
